[build-system]
requires = ["setuptools>=67.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "falcon_mark"
# authors = [
#   { name="", email="" },
# ]
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pytz",
    "streamlit",
    "pymilvus",
    "pydantic",
]
version = "0.0.1"

[project.optional-dependencies]
test = [
    "ruff",
    "pytest",
]


# [project.urls]
# "Homepage"          = ""
# "Docs: User Guide"  = ""
# "Source Code"       = ""

[project.scripts]
init_falcon_mark = "falcon_mark.__main__:main"
